heat_template_version: 2018-09-21

description:
  A simple Heat template that spins up a 3 Tier App with 1 Web Server, 1 App Server,
  and 1 DB Server on logical networks and attaches them to security groups (HOT template in YAML).

parameters:
  external_network_id:
    type: string
    label: ext-net
    description: UUID of a Neutron external network
    default: 4bc06615-471c-4c1b-9938-fe734e573195

  web_image:
    type: string
    description: Name of image to use for servers
    default: cirros_new 

  app_image:
    type: string
    description: Name of image to use for servers
    default: cirros_new

  db_image:
    type: string
    description: Name of image to use for servers
    default: cirros_new

resources:
  # Create the web logical switch and configure DHCP.
  web_network_01:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: web-network-01
  web_subnet_01:
    type: OS::Neutron::Subnet
    properties:
      name: web-subnet-01
      cidr: 172.16.10.0/24
      dns_nameservers: [192.168.110.10]
      enable_dhcp: true
      gateway_ip: 172.16.10.1
      network_id: { get_resource: web_network_01 }

  # Create the app logical switch and configure DHCP.
  app_network_01:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: app-network-01
  app_subnet_01:
    type: OS::Neutron::Subnet
    properties:
      name: app-subnet-01
      cidr: 172.16.20.0/24
      dns_nameservers: [192.168.110.10]
      enable_dhcp: true
      gateway_ip: 172.16.20.1
      network_id: { get_resource: app_network_01 }

  # Create the db logical switch and configure DHCP.
  db_network_01:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: db-network-01
  db_subnet_01:
    type: OS::Neutron::Subnet
    properties:
      name: db-subnet-01
      cidr: 172.16.30.0/24
      dns_nameservers: [192.168.110.10]
      enable_dhcp: true
      gateway_ip: 172.16.30.1
      network_id: { get_resource: db_network_01 }

  # Create router, add internal interfaces for 3 tiers, and also an uplink.
  heat_router_01:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      name: LBaaS-Three-Tier_Router
      value_specs: {router_type: exclusive}
  heat_router_01_gw:
    type: OS::Neutron::RouterGateway
    properties:
      network_id: {get_param: external_network_id}
      router_id: { get_resource: LBaaS-Three-Tier_Router }
  heat_router_int0:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: LBaaS-Three-Tier_Router }
      subnet_id: { get_resource: web_subnet_01 }
  heat_router_int1:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: LBaaS-Three-Tier_Router }
      subnet_id: { get_resource: app_subnet_01 }
  heat_router_int2:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: LBaaS-Three-Tier_Router }
      subnet_id: { get_resource: db_subnet_01 }

  # Create security groups for the tiers.
  db_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow sql traffic from web tier
      name: db-security-group
      rules:
        - remote_ip_prefix: { get_attr: [ app_subnet_01, cidr ] }
          protocol: tcp
          port_range_min: 3306
          port_range_max: 3306

  web_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow web traffic from anywhere
      name: web-security-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22

  app_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow app traffic from web tier
      name: app-security-group
      rules:
        - remote_ip_prefix: { get_attr: [ web_subnet_01, cidr ] }
          protocol: tcp
          port_range_min: 8443
          port_range_max: 8443

  # Create ports on web switch.
  web-svr-01_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: web_network_01 }
      security_groups:
        - { get_resource: web_security_group }
  web-svr-01_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network_id}
      port_id: { get_resource: web-svr-01_port0 }

  web-svr-02_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: web_network_01 }
      security_groups:
        - { get_resource: web_security_group }
  web-svr-02_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network_id}
      port_id: { get_resource: web-svr-02_port0 }

  # Create port(s) on app switch.
  app-svr-01_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: app_network_01 }
      security_groups:
        - { get_resource: app_security_group }

  # Create port(s) on db switch.
  db-svr-01_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: db_network_01 }
      security_groups:
        - { get_resource: db_security_group }

  # Provision instances.
  db-svr-01:
    type: OS::Nova::Server
    properties:
      name: db-instance-01
      image: { get_param: db_image }
      flavor: m1.small
      networks:
        - port: { get_resource: db-svr-01_port0 }

  app-svr-01:
    type: OS::Nova::Server
    depends_on: db-svr-01
    properties:
      name: app-instance-01
      image: { get_param: app_image }
      flavor: m1.small
      networks:
        - port: { get_resource: app-svr-01_port0 }

  web-svr-01:
    type: OS::Nova::Server
    depends_on: app-svr-01
    properties:
      name: web-instance-01
      image: { get_param: web_image }
      flavor: m1.small
      networks:
        - port: { get_resource: web-svr-01_port0 }

  web-svr-02:
    type: OS::Nova::Server
    depends_on: app-svr-01
    properties:
      name: web-instance-02
      image: { get_param: web_image }
      flavor: m1.small
      networks:
        - port: { get_resource: web-svr-02_port0 }

#Create Load Balancer
  load_balancer:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      vip_subnet: { get_resource: web_subnet_01 }

  listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: { get_resource: load_balancer }
      protocol: HTTP
      protocol_port: 80

  lb_pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      protocol: HTTP
      lb_algorithm: ROUND_ROBIN
      listener: { get_resource: listener }

  monitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      type: HTTP
      delay: 10
      max_retries: 5
      timeout: 10
      pool: { get_resource: lb_pool }

#Add web instances to LBaaS Pool
  WebPoolMember1:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: lb_pool }
      address: { get_attr: [web-svr-01, first_address]}
      subnet: { get_resource: web_subnet_01}
      protocol_port: 80

  WebPoolMember2:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: lb_pool }
      address: { get_attr: [web-svr-02, first_address]}
      subnet: { get_resource: web_subnet_01}
      protocol_port: 80

  WebLBFloatingIP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network_id}

  AssocWebLBFloatingIP:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: WebLBFloatingIP }
      port_id: { get_attr: [ load_balancer, vip_port_id ] }

outputs:
  WebLBFloatingIP:
    description: Floating IP of Web Tier Load Balancer
    value: { get_attr: [WebLBFloatingIP, floating_ip_address] }